### ISSUE TITLE
nephelometric turbidity units

### ISSUE THREAD

**Issue by timbrisc** [ucum-org/ucum#220]
*Issue migrated from trac ticket # 5822*

**component:** organization | **priority:** minor | **keywords:** NTU

#### 2022-06-07 20:46:00: william.hess@fda.hhs.gov created the issue

___
> UCUM Board needs to provide input on this. NTU stands for Nephelometric Turbidity Unit and signifies that the instrument is measuring scattered light from the sample at a 90-degree angle from the incident light.  FNU stands for Formazin Nephelometric Units and also signifies that the instrument is measuring scattered light from the sample at a 90-degree angle from the incident light. FNU is most often used when referencing the ISO 7027 (European) turbidity method. NTU is most often used when referencing the USEPA Method 180.1 or Standard Methods For the Examination of Water and Wastewater. 
> When formazin was initially adopted as the primary reference standard for turbidity, units of FTU or Formazin Turbidity Units were used. These units, however, do not specify how the instrument measures the sample.
> 
> FAU or Formazin Attenuation Units signify that the instrument is measuring the decrease in transmitted light through the sample at an angle of 180 degrees to the incident light. This type of measurement is often made in a spectrophotometer or colorimeter and is not considered a valid turbidity measurement by most regulatory agencies.
> 
>  A JTU or Jackson Turbidity Unit is a historical unit used when measurements were made visually using a Jackson Candle Turbidimeter. Water was poured into a tube until a flame underneath the tube could no longer be distinguished.
> 
> The turbidity units NTU, FNU, FTU, AND FAU are all based on calibrations using the same formazin primary standards. Therefore when a formazin standard is measured, the value for each of these units will be the same, however the value on samples may differ significantly.
> 
> This new concept is needed to support the U.S. Food and Drug Administration Pharmaceutical Quality Chemistry Manufacturing and Control (PQ/CMC) initiative. Please see https://www.regulations.gov/document/FDA-2022-N-0297-0001, which in part, states:
> 
> "PQ/CMC is a term used to describe manufacturing and testing data of pharmaceutical products. PQ/CMC encompasses topics such as drug stability, quality specification, batch formula, and batch analysis, which are important aspects of drug development. PQ/CMC plays an integral part in the regulatory review process and life cycle management of pharmaceutical products. The development of a structured format for PQ/CMC data will enable consistency in the content and format of PQ/CMC data submitted, thus providing a harmonized language for submission content, allowing reviewers to query the data, and, in general, contributing to a more efficient and effective regulatory decision-making process by creating a standardized data dictionary.
> 
> The impetus for this standardization effort was the provisions from the 2012 Food and Drug Administration Safety and Innovation Act (Pub. L. 112-144), which authorized the Agency to require certain submissions to be submitted in a specified electronic format. PQ/CMC standardization supports FDA's regulatory needs in receiving structured and standardized data in pharmaceutical quality and includes two objectives: (1) To standardize the pharmaceutical quality data that is currently received by FDA in eCTD Module 3 from the sponsoring organizations, and (2) to use these structured elements and develop a FHIR data exchange solution."
>

**Comment by gschadow** [comment]
Interesting stuff. I recently reckoned that you distinguish a solution from a suspension or emulsion by measuring turbidity (vs. clearness). Seems like it's actually a thing.

What are the mathematic properties of these units that would allow them to be part of a system of units?

This might actually bring up a more general consideration. It touches on "procedure defined units" but that is a term of jargon to begin with, because all units that are actually defined are necessarily defined by some procedure. I think what's going on here is that some phenomena we make accessible to measurement developing a comparable unit standard, are great, but they do not interact with other units in a system.

I think this is where the crux really lies. You may be a unit, and that is great. But do you have any systematic relationships with other units that are not just intrinsic but extrinsically useful? 

By "just intrinsic" I mean of course to the extent that the new unit 's definition depends on standard units, it is systematically related. My example is always to measure hairfall as the mass of of hair falling off someone's head in a week. Those use "day" and "mg" units of measure. Sure, but the resulting unit cannot be used much in computing anything else with them. They are just there. And of course, someone could make a derived unit from it, but no derivation ever brings this unit back into contact with other units and kinds of quantities. It always produces more ideosyncratic kinds of quantities. 

I think this is a very fundamental property of systematic units, perhaps one can call those oddball unit "ideosyncratic" units. We need not deny that they are units, but they don't communicate outside of their own ideosyncratic lineage.

**Comment by gschadow** [comment]
This is also a duplicate of #173 and like I said all of that should be merged with #215 and #214 also.

**Comment by gschadow** [comment]
How can I merge these 3 tickets so only one is left? This has been open for a long time. We were promised that somehow the new approach to everything would bring proposals forward faster. But it seems like there is no way to act on any of them. #246 badly needs some attention.

**Comment by dr-shorthair** [comment]
It appears that permission to merge into the `main` branch is currently limited. 
@timbrisc is that correct?

**Comment by dr-shorthair** [comment]
I don't know of any way to formally merge Issues. 
When I have hit this elsewhere, I've manually copied the key information over into one Issue and closed the others.

**Comment by gschadow** [comment]
https://en.wikipedia.org/wiki/Turbidity

I would propose:

- [FNU] - Formazin Nephelometric Units (FNU) from ISO 7027
- [NPU] - Nephelometric Turbidity Units (NTU) from [USEPA Method 180.1](https://www.epa.gov/sites/default/files/2015-08/documents/method_180-1_1993.pdf)
- [JTU] - Apparently this is really old and unreliable

There is a remaining argument though where it is alleged that NPUs do not signify comparable results, in other words that the USEPA Method 180.1 does not lead to reproducible results?

**Comment by SRKid** [comment]
Good afternoon,

I concur with Gunther’s proposal.

Thanks,
Bill


***@***.***



From: Gunther Schadow ***@***.***>
Sent: Tuesday, July 25, 2023 4:25 PM
To: ucum-org/ucum ***@***.***>
Cc: Hess, William A ***@***.***>; Assign ***@***.***>
Subject: [EXTERNAL] Re: [ucum-org/ucum] nephelometric turbidity units (Issue #220)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.


https://en.wikipedia.org/wiki/Turbidity

I would propose:

  *   [FNU] - Formazin Nephelometric Units (FNU) from ISO 7027
  *   [NPU] - Nephelometric Turbidity Units (NTU) from USEPA Method 180.1<https://www.epa.gov/sites/default/files/2015-08/documents/method_180-1_1993.pdf>
  *   [JTU] - Apparently this is really old and unreliable

There is a remaining argument though where it is alleged that NPUs do not signify comparable results, in other words that the USEPA Method 180.1 does not lead to reproducible results?

**Comment by timbrisc** [comment]
Included in v2.2 release
